title: Sophia Hu # your name (or website title) here
logo: "/images/cat-circle.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About 
  <br>  Recent graduate of University of Maryland, College Park with a BSc in mathematics-statistics and computer science. My research interests includes machine learning, HCI, data visualization, and AI.  <br>
  
  <br> Looking for full-time roles in data science and software engineering!
  <br>
  <a href="https://www.linkedin.com/in/sophia-h-509267200/">LinkedIn</a> 
  <a href="https://github.com/sophiaahh">Github</a> 
  
  
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
